/* QC BƯỚC 1 - XUẤT CẤU TRÚC DATABASE SX ĐỂ DỰNG LẠI CHO QC
   Chạy trên project Supabase của SX, SQL Editor, New query, dán, Run.
   Kết quả là 1 ô chữ dài, bấm vào ô rồi Copy, sang project QC dán rồi Run.
   Chỉ đọc, không sửa gì ở database SX.
   Câu lệnh cố ý không chứa các ký tự dễ làm SQL Editor hiểu nhầm. Dấu chấm
   phẩy trong lệnh xuất ra được ghi tạm là ký tự § rồi đổi lại ở cuối, tiêu
   đề chú thích ghép bằng chr(47) chr(42). */
with
bang as (
  select c.oid, c.relname
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
),
cot as (
  select b.relname, a.attnum, pg_get_expr(ad.adbin, ad.adrelid) as mac_dinh,
         format_type(a.atttypid, a.atttypmod) as kieu, a.attname, a.attnotnull, a.attidentity
  from bang b
  join pg_attribute a on a.attrelid = b.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = b.oid and ad.adnum = a.attnum
),
tao_bang as (
  select relname, format(E'create table if not exists public.%I (\n  %s\n)§', relname,
    string_agg(
      quote_ident(attname) || ' ' ||
      case when mac_dinh like 'nextval(%' then
             case kieu when 'bigint' then 'bigserial' when 'integer' then 'serial'
                       when 'smallint' then 'smallserial' else kieu end
           else kieu end ||
      case attidentity when 'a' then ' generated always as identity'
                       when 'd' then ' generated by default as identity' else '' end ||
      case when mac_dinh is not null and mac_dinh not like 'nextval(%' then ' default ' || mac_dinh else '' end ||
      case when attnotnull and mac_dinh like 'nextval(%' then ''
           when attnotnull then ' not null' else '' end,
      E',\n  ' order by attnum)) as sql
  from cot group by relname
),
rang_buoc as (
  /* xoá trước rồi tạo lại (cascade: khoá ngoại phụ thuộc bị xoá theo, được tạo lại ở phần khoá ngoại)
     -> chạy lại nhiều lần không lỗi, không cần khối DO */
  select con.contype, b.relname, con.conname,
         format('alter table public.%I drop constraint if exists %I cascade§ alter table public.%I add constraint %I %s§',
                b.relname, con.conname, b.relname, con.conname, pg_get_constraintdef(con.oid)) as sql
  from pg_constraint con join bang b on b.oid = con.conrelid
  where con.contype in ('p', 'u', 'c', 'f')
),
chi_muc as (
  select i.indexname,
         replace(replace(i.indexdef, 'CREATE INDEX ', 'CREATE INDEX IF NOT EXISTS '),
                 'CREATE UNIQUE INDEX ', 'CREATE UNIQUE INDEX IF NOT EXISTS ') || '§' as sql
  from pg_indexes i
  where i.schemaname = 'public'
    and i.indexname not in (select conname from pg_constraint)
),
bat_rls as (
  select format('alter table public.%I enable row level security§', relname) as sql
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),
quyen as (
  select format('drop policy if exists %I on public.%I§', p.policyname, p.tablename) || E'\n' ||
         format('create policy %I on public.%I as %s for %s to %s%s%s§',
           p.policyname, p.tablename, lower(p.permissive), p.cmd,
           array_to_string(p.roles, ', '),
           case when p.qual is not null then ' using (' || p.qual || ')' else '' end,
           case when p.with_check is not null then ' with check (' || p.with_check || ')' else '' end) as sql
  from pg_policies p
  where p.schemaname = 'public'
),
ham as (
  select pg_get_functiondef(p.oid) || '§' as sql
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
),
du_lieu as (
  /* 2 bảng cấu hình dùng chung: thang xếp loại và ngày lễ */
  select format('insert into public.rating_config select * from json_populate_record(null::public.rating_config, %L) on conflict do nothing§',
                row_to_json(x)::text) as sql
  from public.rating_config x
  union all
  select format('insert into public.holidays select * from json_populate_record(null::public.holidays, %L) on conflict do nothing§',
                row_to_json(x)::text)
  from public.holidays x
),
dat_lai_dem as (
  /* chép kèm id thì đẩy bộ đếm tự tăng lên, không lần thêm sau bị trùng id */
  select format('select setval(pg_get_serial_sequence(%L, %L), coalesce((select max(%I) from public.%I), 0) + 1, false)§',
                'public.' || quote_ident(relname), attname, attname, relname) as sql
  from cot
  where mac_dinh like 'nextval(%' and relname in ('rating_config', 'holidays')
),
tat_ca as (
  select
    E'' || chr(47) || chr(42) || ' DỰNG DATABASE QC - tạo từ database SX lúc ' || to_char(now(), 'DD/MM/YYYY HH24:MI') || E' ' || chr(42) || chr(47) || E'\n\n'
    || E'' || chr(47) || chr(42) || ' 1. Bảng ' || chr(42) || chr(47) || E'\n' || (select string_agg(sql, E'\n\n' order by relname) from tao_bang) || E'\n\n'
    || E'' || chr(47) || chr(42) || ' 2. Khoá chính, không trùng, kiểm tra ' || chr(42) || chr(47) || E'\n'
    || coalesce((select string_agg(sql, E'\n' order by relname, conname) from rang_buoc where contype in ('p', 'u', 'c')), '') || E'\n\n'
    || E'' || chr(47) || chr(42) || ' 3. Khoá ngoại ' || chr(42) || chr(47) || E'\n'
    || coalesce((select string_agg(sql, E'\n' order by relname, conname) from rang_buoc where contype = 'f'), '') || E'\n\n'
    || E'' || chr(47) || chr(42) || ' 4. Chỉ mục ' || chr(42) || chr(47) || E'\n'
    || coalesce((select string_agg(sql, E'\n' order by indexname) from chi_muc), '') || E'\n\n'
    || E'' || chr(47) || chr(42) || ' 5. Bật RLS + quyền truy cập ' || chr(42) || chr(47) || E'\n'
    || coalesce((select string_agg(sql, E'\n') from bat_rls), '') || E'\n'
    || coalesce((select string_agg(sql, E'\n') from quyen), '') || E'\n\n'
    || E'' || chr(47) || chr(42) || ' 6. Hàm (vd check_app_password) ' || chr(42) || chr(47) || E'\n'
    || coalesce((select string_agg(sql, E'\n\n') from ham), '') || E'\n\n'
    || E'' || chr(47) || chr(42) || ' 7. Dữ liệu cấu hình dùng chung ' || chr(42) || chr(47) || E'\n'
    || coalesce((select string_agg(sql, E'\n') from du_lieu), '') || E'\n'
    || coalesce((select string_agg(sql, E'\n') from dat_lai_dem), '') || E'\n\n'
    || E'' || chr(47) || chr(42) || ' 8. Kho ảnh 5S ' || chr(42) || chr(47) || E'\n'
    || 'insert into storage.buckets (id, name, public) values (' || quote_literal('s5-photos') || ', '
    || quote_literal('s5-photos') || ', true) on conflict (id) do nothing§' || E'\n' as t
)
select replace(t, '§', chr(59)) as lenh_tao_database_qc from tat_ca;
