-- ═══════════════════════════════════════════════════════════════
-- QC BƯỚC 1: XUẤT CẤU TRÚC DATABASE SX ĐỂ DỰNG LẠI CHO QC
-- ═══════════════════════════════════════════════════════════════
-- Chạy trên project Supabase CỦA SX (project hiện tại):
--   SQL Editor → New query → dán file này → Run
-- Kết quả là 1 ô chữ dài: bấm vào ô → Copy. Đó chính là các lệnh tạo bảng.
-- Sang project Supabase CỦA QC: SQL Editor → New query → dán → Run.
--
-- Câu lệnh này CHỈ ĐỌC, không sửa gì ở database SX.
-- Lấy y hệt: cột, kiểu, mặc định, khoá, ràng buộc, chỉ mục, bật RLS, quyền
-- truy cập (policy), hàm (vd check_app_password). KHÔNG chép dữ liệu nhân
-- viên/đánh giá/5S... của SX - QC bắt đầu trống - trừ 2 bảng cấu hình dùng
-- chung là rating_config (thang xếp loại) và holidays (ngày lễ công ty).
-- ═══════════════════════════════════════════════════════════════
with
bang as (
  select c.oid, c.relname
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
),
cot as (
  select b.relname, a.attnum, pg_get_expr(ad.adbin, ad.adrelid) as mac_dinh,
         format_type(a.atttypid, a.atttypmod) as kieu, a.attname, a.attnotnull, a.attidentity
  from bang b
  join pg_attribute a on a.attrelid = b.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = b.oid and ad.adnum = a.attnum
),
tao_bang as (
  -- cột tự tăng (nextval) -> viết lại thành serial/bigserial để database mới tự tạo sequence
  select relname, format(E'create table if not exists public.%I (\n  %s\n);', relname,
    string_agg(
      quote_ident(attname) || ' ' ||
      case when mac_dinh like 'nextval(%' then
             case kieu when 'bigint' then 'bigserial' when 'integer' then 'serial'
                       when 'smallint' then 'smallserial' else kieu end
           else kieu end ||
      case attidentity when 'a' then ' generated always as identity'
                       when 'd' then ' generated by default as identity' else '' end ||
      case when mac_dinh is not null and mac_dinh not like 'nextval(%' then ' default ' || mac_dinh else '' end ||
      case when attnotnull and mac_dinh is distinct from null and mac_dinh like 'nextval(%' then ''
           when attnotnull then ' not null' else '' end,
      E',\n  ' order by attnum)) as sql
  from cot group by relname
),
rang_buoc as (
  -- p = khoá chính, u = không trùng, c = kiểm tra, f = khoá ngoại (để sau cùng)
  select con.contype, b.relname, con.conname,
         format('alter table public.%I add constraint %I %s;', b.relname, con.conname, pg_get_constraintdef(con.oid)) as sql
  from pg_constraint con join bang b on b.oid = con.conrelid
  where con.contype in ('p', 'u', 'c', 'f')
),
chi_muc as (
  select i.indexname, i.indexdef || ';' as sql
  from pg_indexes i
  where i.schemaname = 'public'
    and i.indexname not in (select conname from pg_constraint)
),
bat_rls as (
  select format('alter table public.%I enable row level security;', relname) as sql
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),
quyen as (
  select format('drop policy if exists %I on public.%I;', p.policyname, p.tablename) || E'\n' ||
         format('create policy %I on public.%I as %s for %s to %s%s%s;',
           p.policyname, p.tablename, lower(p.permissive), p.cmd,
           array_to_string(p.roles, ', '),
           case when p.qual is not null then ' using (' || p.qual || ')' else '' end,
           case when p.with_check is not null then ' with check (' || p.with_check || ')' else '' end) as sql
  from pg_policies p
  where p.schemaname = 'public'
),
ham as (
  select pg_get_functiondef(p.oid) || ';' as sql
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')   -- bỏ hàm của extension
),
du_lieu as (
  -- 2 bảng cấu hình dùng chung: thang xếp loại và ngày lễ
  select format('insert into public.rating_config select * from json_populate_record(null::public.rating_config, %L) on conflict do nothing;',
                row_to_json(x)::text) as sql
  from public.rating_config x
  union all
  select format('insert into public.holidays select * from json_populate_record(null::public.holidays, %L) on conflict do nothing;',
                row_to_json(x)::text)
  from public.holidays x
),
dat_lai_dem as (
  -- chép kèm id thì phải đẩy bộ đếm tự tăng lên, không lần thêm sau bị trùng id
  select format('select setval(pg_get_serial_sequence(%L, %L), coalesce((select max(%I) from public.%I), 0) + 1, false);',
                'public.' || quote_ident(relname), attname, attname, relname) as sql
  from cot
  where mac_dinh like 'nextval(%' and relname in ('rating_config', 'holidays')
)
select
  E'-- ═══ QC BƯỚC 2: DỰNG DATABASE QC (tạo từ database SX lúc ' || to_char(now(), 'DD/MM/YYYY HH24:MI') || E') ═══\n'
  || E'-- Chạy trên project Supabase CỦA QC. Chạy lại nhiều lần không sao.\n\n'
  || E'-- 1. Bảng\n' || (select string_agg(sql, E'\n\n' order by relname) from tao_bang) || E'\n\n'
  || E'-- 2. Khoá chính, không trùng, kiểm tra\n'
  || coalesce((select string_agg(format(E'do $$ begin %s exception when duplicate_object or duplicate_table or invalid_table_definition then null; end $$;', sql), E'\n' order by relname, conname)
               from rang_buoc where contype in ('p', 'u', 'c')), '') || E'\n\n'
  || E'-- 3. Khoá ngoại\n'
  || coalesce((select string_agg(format(E'do $$ begin %s exception when duplicate_object or invalid_table_definition then null; end $$;', sql), E'\n' order by relname, conname)
               from rang_buoc where contype = 'f'), '') || E'\n\n'
  || E'-- 4. Chỉ mục\n'
  || coalesce((select string_agg(replace(replace(sql, 'CREATE INDEX ', 'CREATE INDEX IF NOT EXISTS '), 'CREATE UNIQUE INDEX ', 'CREATE UNIQUE INDEX IF NOT EXISTS '), E'\n' order by indexname) from chi_muc), '') || E'\n\n'
  || E'-- 5. Bật RLS + quyền truy cập\n'
  || coalesce((select string_agg(sql, E'\n') from bat_rls), '') || E'\n'
  || coalesce((select string_agg(sql, E'\n') from quyen), '') || E'\n\n'
  || E'-- 6. Hàm (vd check_app_password - mật khẩu quản lý)\n'
  || coalesce((select string_agg(sql, E'\n\n') from ham), '') || E'\n\n'
  || E'-- 7. Dữ liệu cấu hình dùng chung\n'
  || coalesce((select string_agg(sql, E'\n') from du_lieu), '') || E'\n'
  || coalesce((select string_agg(sql, E'\n') from dat_lai_dem), '') || E'\n\n'
  || E'-- 8. Kho ảnh 5S\n'
  || E'insert into storage.buckets (id, name, public) values (''s5-photos'', ''s5-photos'', true) on conflict (id) do nothing;\n'
  as lenh_tao_database_qc;
